export const SET_LOCATION_SUCCESS = "SET_LOCATION_SUCCESS";
export const LOAD_LOCATIONS_SUCCESS = "LOAD_LOCATIONS_SUCCESS";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const ERROR_ENCOUNTERED = "ERROR_ENCOUNTERED";
